### ISSUE TITLE
Image Rotation and Counter Points

### ISSUE THREAD

**Issue by HairNemesis** [qupath/qupath#193]
Hello,

In the process of grading bowel inflammation which includes leukocyte infiltrates.  First step is to rotate the image to orientate the mucosa (epithelial layer) up as it's much easier to assess.  Generally involves a +/- 90 degree rotation.  Afterwards open counter tool and begin marking infiltrates.  However the counter will register a click but no corresponding point will not appear on the image.  Similarly converting detections to points does not display points either.

Interestingly the points will display when the image is is rotated to <90 degrees either way.  Furthermore the points will scale down with as the image is rotated towards to the original orientation.  This is best seen when the smallest point size is selected.

Otherwise a great program and is proving immensely helpful.  Many thanks.

**Comment by petebankhead** [comment]
What a curious bug... didn't know about it, but I could replicate it and noticed that the points also increased in size as the rotation got closer to 90 degrees.

Anyhow, both phenomena had the same cause and it should be fixed in the next version. You can try it out early, including the fix, if you follow the instructions at the bottom of [this page](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html).

(There should be a few other fixes there related to the _Point tool_ - such as when deleting a point with _Alt_ pressed might enthusiastically remove a neighboring point, but not actually the one you were aiming for)

**Comment by HairNemesis** [comment]
Due to the problem with straight line ROIs shifting when reloading previously-saved image data (Issue #71), I've already upgraded to v0.1.3 ( #71 fixed).  Unfortunately the 90 degree point bug remains in effect.

**Comment by petebankhead** [comment]
If you've already got everything set up in _GitHub Desktop_, there should be a _Fetch origin_ button towards the top right - click that, and then again if the text changes to _Pull origin_.

Then, with the latest code successfully pulled down, in the _History_ tab on the left the top entry should be _Fixed point painting bug_.

If you follow the rest of the instructions to build QuPath, you should end up with a version that works.  I've tested it on Windows and Mac and it is working here.

**Comment by HairNemesis** [comment]
Fixed, Cheers.
