### ISSUE TITLE
TMA dearrayer dosen't work

### ISSUE THREAD

**Issue by takakono** [qupath/qupath#329]
**Describe the bug**
TMA dearrayer doesn't work  from the first step

**To Reproduce****Expected behavior**
When I run the TMA dearrayer on an H+E image of my TMA slide, it does not pick up any of the cores. Any ideas for how to get it working? 

I have set ' Brightfield H&E' as the slide image and 8GB memory for Qupath.
Slide image  file using for Qupath is Scan Scope Virtual Slide.
I could do another analysis like a positive cell counts on HE or IHC.

**Desktop (please complete the following information):**
Windows 7
QuPath Version [0.1.2]

![QuPath TMA dearrayer](https://user-images.githubusercontent.com/51498119/59213559-06e55d80-8b6a-11e9-995a-4bbc8613a181.PNG)

**Comment by petebankhead** [comment]
The problem may be that the file format you are using results in a large black region that is probably confusing the dearrayer threshold. If you try in v0.2.0-m2 you may find that this background not included and the problem is resolved.

If so, it should work in the next release.

**Comment by takakono** [comment]
Thank you for prompt reply.
I have updated Qupath and tried TMA dearryer again, as same as I mentioned above.
But it still doesn't work.

![new version QuPath TMA dearrayer work flow](https://user-images.githubusercontent.com/51498119/59235646-39fa1200-8ba7-11e9-9c6b-aea5593b341b.PNG)
![new version QuPath TMA dearrayer](https://user-images.githubusercontent.com/51498119/59235653-40888980-8ba7-11e9-9291-27aee29b9e84.PNG)

**Comment by petebankhead** [comment]
Ok, but potentially for a different reason - from the thumbnail I can see that at least in v0.2.0-m2 the image is cropped.

There are many discussions about the TMA dearrayer
* On GitHub https://github.com/qupath/qupath/search?q=tma&type=Issues
* On the new forum https://forum.image.sc/search?q=tma
* On the old forum https://groups.google.com/forum/#!searchin/qupath-users/tma$20dearrayer%7Csort:date

It would be helpful to know what you have tried, or if nothing from the links works if you can share the full image. Assuming that the image type is definitely set to brightfield, the main thing you can do is adjust the core size to see if that helps - otherwise the links should contain some discussions of (admittedly) awkward ways to create a TMA grid manually.

The built-in TMA dearraying algorithm works for many cases, but not all. I intend to add further options for dearraying in the future, but this is one thing amidst a very long backlog and I can't give an estimate when yet.

**Comment by 2jour** [comment]
Try .9 mm for TMA core diameter

**Comment by Svidro** [comment]
I suspect it might be slightly smaller than 0.9 (based on a stickynote ruler on the screen), but I think 2jour is on the right path.

**Comment by takakono** [comment]
Thank you for your help.
It works after I changed TMA core diameter as your advice (When it didn't work, I had set core diameter 0.6mm).
Thank you for all of your helpful advice!

![TMA](https://user-images.githubusercontent.com/51498119/59290530-9b64c400-8c2d-11e9-8b26-56d11003e5fe.PNG)
