### ISSUE TITLE
Spurious 'Physical memory usage is too high' errors when training a pixel classifier

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#856]
## Bug report

**Describe the bug**
QuPath sometimes reports OutOfMemoryErrors when training or running a pixel classifier in situations where the memory use is not actually too high.

This has been particularly evident on an M1 MacBook Pro, and seems related to https://github.com/bytedeco/javacpp/issues/468 and https://github.com/bytedeco/javacpp/issues/516

The errors look like this:

```
ERROR: Error requesting tile classification: 
java.io.IOException: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (16451M) > maxPhysicalBytes (16384M)
    at qupath.lib.classifiers.pixel.PixelClassificationImageServer.readTile(PixelClassificationImageServer.java:314)
    at qupath.lib.images.servers.AbstractTileableImageServer.getTile(AbstractTileableImageServer.java:184)
    at qupath.lib.images.servers.AbstractTileableImageServer.readBufferedImage(AbstractTileableImageServer.java:238)
    at qupath.lib.images.servers.AbstractTileableImageServer.readBufferedImage(AbstractTileableImageServer.java:56)
    at qupath.lib.gui.viewer.overlays.PixelClassificationOverlay.lambda$requestTile$5(PixelClassificationOverlay.java:547)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
  Caused by Physical memory usage is too high: physicalBytes (16451M) > maxPhysicalBytes (16384M)        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:712)
        at org.bytedeco.javacpp.Pointer.init(Pointer.java:126)
        at org.bytedeco.opencv.opencv_core.Mat.allocate(Native Method)
        at org.bytedeco.opencv.opencv_core.Mat.<init>(Mat.java:241)
        at qupath.opencv.ml.OpenCVClassifiers$AbstractOpenCVClassifierML.predictWithLock(OpenCVClassifiers.java:468)
        at qupath.opencv.ml.OpenCVClassifiers$ANNClassifierCV.predictWithLock(OpenCVClassifiers.java:1425)
        at qupath.opencv.ml.OpenCVClassifiers$AbstractOpenCVClassifierML.predict(OpenCVClassifiers.java:442)
        at qupath.opencv.ops.ImageOps$ML$StatModelOp.apply(ImageOps.java:2812)
        at qupath.opencv.ops.ImageOps$Core$SequentialMultiOp.apply(ImageOps.java:2294)
        at qupath.opencv.ops.ImageOps$ChannelImageDataOp.apply(ImageOps.java:424)
        at qupath.opencv.ml.pixel.OpenCVPixelClassifier.applyClassification(OpenCVPixelClassifier.java:104)
        at qupath.lib.classifiers.pixel.PixelClassificationImageServer.readTile(PixelClassificationImageServer.java:299)
        at qupath.lib.images.servers.AbstractTileableImageServer.getTile(AbstractTileableImageServer.java:184)
        at qupath.lib.images.servers.AbstractTileableImageServer.readBufferedImage(AbstractTileableImageServer.java:238)
        at qupath.lib.images.servers.AbstractTileableImageServer.readBufferedImage(AbstractTileableImageServer.java:56)
        at qupath.lib.gui.viewer.overlays.PixelClassificationOverlay.lambda$requestTile$5(PixelClassificationOverlay.java:547)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
1. Open OS-1.ndpi on an M1 Mac, set to have a maximum of 4GB RAM for QuPath
2. Start training a pixel classifier (default resolution and settings)
3. Zoom out to force preview classification across the full image
4. Open the log & await the error
    * If no error appears, adjust training annotations if needed to create a new classifier (it usually doesn't take long)
5. Check Activity Monitor to confirm that QuPath does not seem to be using a particularly large amount of memory

**Expected behavior**
Pixel classification continues without error for as long as its real memory use remains reasonable.

**Desktop (please complete the following information):**
 - OS: macOS, ARM
 - QuPath Version 0.3.0

**Additional context**
Following the suggestion in https://github.com/bytedeco/javacpp/issues/516 a workaround is to add the line 
```
java-options=-Dorg.bytedeco.javacpp.maxPhysicalBytes=0
```
at the end of the *QuPath.app/Contents/app/QuPath.cfg* file.

This turns off the check that reports the error, but could be risky to introduce as a default - so this Issue was created to document the problem for now, and a workaround where needed.

**Comment by saudet** [comment]
Is this still a problem with JavaCPP 1.5.6? The new default value should be large enough, even on M1.
Please let me know if this is still an issue though, and we'll need to figure out something there.

/cc @balgillo

**Comment by petebankhead** [comment]
Hi @saudet thanks very much for checking this.

Yes, it is still a problem with JavaCPP 1.5.6 (although less often, with the larger limit). I have just confirmed it following the steps to reproduce above and the [OS-1.ndpi](https://openslide.cs.cmu.edu/download/openslide-testdata/Hamamatsu/OS-1.ndpi) image from openslide.org

![Screenshot 2022-01-21 at 05 53 09](https://user-images.githubusercontent.com/4690904/150473986-f94358f8-f834-46d6-b502-d80d040829a6.png)

![Screenshot 2022-01-21 at 05 50 03](https://user-images.githubusercontent.com/4690904/150474005-3aae13a4-6bed-44f9-af05-fb0b677abf0b.png)

I followed the exact same steps on a 2013 iMac without any problems, so there does seem to be something different on the M1.

Our use may be a little obscure. QuPath's pixel classifier ([docs](https://qupath.readthedocs.io/en/stable/docs/tutorials/pixel_classification.html)) is designed to support interactively training a machine learning classifier. It should support many image types, but is typically used with very large, tiled, multiresolution biomedical images (usually 10-50 GB per 2D image).

The pixel classification uses OpenCV's ML module via JavaCPP, but in principle also supports semantic segmentation using a pretrained deep learning model with OpenCV's DNN module or TensorFlow - JavaCPP is central to it all (thanks!).

In all cases, each required image tile is read on demand and cached as a Java `BufferedImage`. It is converted to an OpenCV `Mat` temporarily for whatever calculations are required, then the end result converted back to a `BufferedImage`. Therefore quite a lot of fairly large `Mat` objects can be generated for the pixels, features and predictions, but closed after use and using `PointerScope` extensively since QuPath v0.3. This seems to be working very well everywhere except on M1.

**Comment by petebankhead** [comment]
I ran [this script](https://gist.github.com/petebankhead/40520366791ef8fe0ab0ca3403812d8d) to print more memory info from Java and JavaCPP.

### MacBook Pro M1
After the errors above:
```
Runtime:
  maxMemory()        	4096 MB
  totalMemory()      	4082 MB
  freeMemory()       	2657.05673980712890625 MB
  Memory used        	1424.94326019287109375 MB

Pointer:
  maxBytes()         	4096 MB
  maxPhysicalBytes() 	16384 MB
  totalBytes()       	0.0015869140625 MB
  physicalBytes()    	19015.328125 MB

  Total count:       	32

Operating system:
  Total:             	16384 MB
  Available:         	14.92578125 MB
```


### 2013 iMac Intel
After the same processing steps, running without problems:
```
Runtime:
  maxMemory()        	4096 MB
  totalMemory()      	4096 MB
  freeMemory()       	2742.839874267578125 MB
  Memory used        	1353.160125732421875 MB

Pointer:
  maxBytes()         	4096 MB
  maxPhysicalBytes() 	16384 MB
  totalBytes()       	0.00140380859375 MB
  physicalBytes()    	5464.46875 MB

  Total count:       	30

Operating system:
  Total:             	32768 MB
  Available:         	194.671875 MB
```

**Comment by saudet** [comment]
BTW, binaries for OpenCV on macosx-arm64 are available in the snapshots: http://bytedeco.org/builds/
Would you mind giving that a try with a native (ARM64) version of the JDK?
At the moment, such builds of the JDK seem to be available from at least Azul and Microsoft, here: 
https://www.azul.com/downloads/?os=macos&architecture=arm-64-bit&package=jdk
https://github.com/microsoft/openjdk-aarch64/releases/tag/jdk-16.0.2-ga

**Comment by petebankhead** [comment]
Thanks, I should have thought of that. I've just tried the ARM64 build from 2021-11-08 and it works beautifully - I couldn't reproduce the issue, and it runs noticeably faster.

I used the old build because it's unfortunately really awkward to build QuPath for M1 - the libraries we use to read whole slide images are stuck on Intel.
* OpenSlide - https://github.com/openslide/openslide / https://github.com/openslide/openslide-java
* Bio-Formats - https://github.com/ome/bioformats (because it uses an older libjpeg-turbo)

I hacked together something that works locally with OpenSlide installed via Homebrew so I could test JavaCPP / OpenCV, but I haven't figured out how to make the whole distribution portable (https://github.com/qupath/qupath/issues/629).

If it's possible to resolve the memory errors via JavaCPP so that it works via Rosetta that would be excellent, but I understand if not - especially since it seems fine in the ARM64 build, and we'll want to use that as soon as we can figure out how.

**Comment by saudet** [comment]
Thanks for testing this out so quickly! So, the issue really is with Rosetta. Obviously, I'd want to have something that works well with Rosetta as well. Let me think about that...

As for OpenSlide and what not, well, packaging this as JavaCPP Presets would be one way to get this going smoothly, but someone would need to spend time on it: https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

**Comment by saudet** [comment]
This should be fixed now, see https://github.com/bytedeco/javacpp/issues/468#issuecomment-1019469099.

**Comment by petebankhead** [comment]
Thanks @saudet I've just tried this with the latest `javacpp-1.5.7-SNAPSHOT-macosx-x86_64.jar` on my M1 MacBook Pro. I do still see the error, but it seems to take longer to reach (I had to train 3 classifiers rather than 2).

```
Runtime:
  maxMemory()        	4096 MB
  totalMemory()      	4088 MB
  freeMemory()       	2722.48044586181640625 MB
  Memory used        	1365.51955413818359375 MB

Pointer:
  maxBytes()         	4096 MB
  maxPhysicalBytes() 	16384 MB
  totalBytes()       	0.00213623046875 MB
  physicalBytes()    	17062.1875 MB

  Total count:       	38

Operating system:
  Total:             	16384 MB
  Available:         	26.12109375 MB
```

**Comment by saudet** [comment]
Hum, maybe the JVM is picking up the old method from the binaries of OpenCV instead.
I'm restarting the builds for OpenCV: https://github.com/bytedeco/javacpp-presets/actions/runs/1706537597
Could you try again with those new snapshots when they are done?

**Comment by petebankhead** [comment]
I deleted the snapshots from my gradle cache, and built QuPath again just now. I'm afraid I still see the same behavior, it still gives the error.

In case I was still somehow using an out-of-date jar, I checked the JavaCPP manifest and see
### JavaCPP
```
Bundle-Version: 1.5.7.202201240730
```

**Comment by saudet** [comment]
This is extremely strange. @balgillo said this isn't happening for him with Rosetta...

**Comment by saudet** [comment]
These are currently the latest snapshots for the binaries of JavaCPP and OpenCV for macosx-x86_64:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.5.7-SNAPSHOT/javacpp-1.5.7-20220124.073227-499-macosx-x86_64.jar
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/opencv/4.5.5-1.5.7-SNAPSHOT/opencv-4.5.5-1.5.7-20220125.171651-133-macosx-x86_64.jar
Make sure all the files that are in ~/.javacpp/cache are identical to the files in these JAR files. If you get any additional files, that's also not a good sign.

**Comment by balgillo** [comment]
> This is extremely strange. @balgillo said this isn't happening for him with Rosetta...

Hi, not sure what you're referring to here.  In our case, we saw JavaCPP v1.5.6 detecting excessively-high physicalBytes under Rosetta, we put in place the workaround:
```
-Dorg.bytedeco.javacpp.maxPhysicalBytes=0
```
... and it's still in place, we haven't tried anything else since.

**Comment by saudet** [comment]
@balgillo Not JavaCPP, you said Rosetta didn't affect the "phys_footprint" (which is a number always larger than then the "internal" one I ended up choosing for JavaCPP 1.5.7), while it appears to affect it for @petebankhead (unless it's just caused by some old binary creeping in from somewhere).

**Comment by balgillo** [comment]
@saudet thanks, understood.  We didn't get to the bottom of what phys_footprint is measuring, only the intention behind it, which is to measure the "true" resource impact of the app

**Comment by saudet** [comment]
Oh, there's OpenBLAS too, forgot about that one. Let me restart that build
as well.

**Comment by saudet** [comment]
Ok, done, make sure the binaries found in this JAR file end up getting loaded:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/openblas/0.3.19-1.5.7-SNAPSHOT/openblas-0.3.19-1.5.7-20220127.123031-179-macosx-x86_64.jar

**Comment by petebankhead** [comment]
I used the jars from your links (in case I was getting old SNAPSHOTs), deleted the JavaCPP cache and I'm afraid that I'm still getting the same errors.

**Comment by saudet** [comment]
This is really strange. I added a unit test for that here:
https://github.com/bytedeco/javacpp/blob/master/src/test/java/org/bytedeco/javacpp/PointerTest.java#L1154-L1177
Could you try to run that and see if it fails under Rosetta?

**Comment by petebankhead** [comment]
I cloned the repo and ran `mvn test`. Everything passed, and I saw printed
```
NoFileBytes
670285824 676003840
```
I'll try to figure out if there's something else I'm doing wrong.

**Comment by petebankhead** [comment]
I've run it several times with different JDKs, both x86_64 and aarch64. Tests have passed every time... except once, using AdoptOpenJDK 16 with Rosetta.

![Screenshot 2022-01-28 at 11 40 01](https://user-images.githubusercontent.com/4690904/151541015-d439dd98-5411-4115-ad08-c91cab4f620c.png)

However I haven't managed to repeat the failure despite repeatedly trying with the same JDK. I am confused...

**Comment by saudet** [comment]
The test isn't perfect, it might fail sometimes because the JVM may not be able to release the memory in time for whatever reason. The fact that it passes most of the time is OK. So that works. However, the base load for "internal" memory seems to be around 680 MB, which sounds big to me, it's typically less than 100 MB, but maybe that's normal for Rosetta, not sure...

**Comment by saudet** [comment]
Maybe there's still some old binary lying around, so try to run that test code, make sure it passes, and right after that don't close the process, but continue to run your test with QuPath. Hopefully the right newer version of Pointer.physicalBytes() sticks around.

**Comment by petebankhead** [comment]
I'm not sure... I'm now trying to run specifically that one test through eclipse, switching between OpenJDK 17 for x86_64 and for aarch64.

It is failing reproducibly for me using `x86_64`, and passing with `aarch64`.
I've added a `System.out.println(System.getProperty("os.arch"));` with failures I see e.g.
```
NoFileBytes
x86_64
420986880 436666368
```
and with successes
```
NoFileBytes
aarch64
36864000 40239104
```

VM args (adjusted so the other tests pass):
```
-ea -Xmx1G -Dorg.bytedeco.javacpp.maxRetries=3
```

Meanwhile I have seen more failures with the full `mvn test`, but it remains inconsistent. However, when it does fail it is always on that test.

**Comment by saudet** [comment]
It looks fine, I wouldn't worry. Maybe we should just check it doesn't increase by 100 MB here instead of only 10 MB:
https://github.com/bytedeco/javacpp/blob/master/src/test/java/org/bytedeco/javacpp/PointerTest.java#L1175

**Comment by petebankhead** [comment]
Thanks, makes sense.

I'm still unable to get things working reliably in QuPath, including after a restart and when keeping the process alive after testing, but I'm not sure what else to try. For QuPath itself, the problem remains pretty obscure (I don't think any users have complained yet).

I wouldn't want this to delay any 1.5.7 release, and I can't be certain any lingering problems aren't on our side anyway - I'm looking forward to the non-SNAPSHOT aarch64 builds being available.

**Comment by saudet** [comment]
Maybe it's a legitimate memory leak in Rosetta? Did you check that? It appears a lot of people are having problems with it, like this: https://feedback-readonly.photoshop.com/conversations/lightroom-classic/lightroom-classic-desktop-disk-readwrite-to-ssd-m1-macs-with-rosetta/5fd7cefe7288d52d004c5a1c

Anyway, I'm waiting after a couple of things myself before the next release of JavaCPP, so if you figure out anything in the next week or so and find something, please do let me know! Thanks

**Comment by petebankhead** [comment]
Thanks @saudet good point! Alas, I'm currently stuck on macOS Big Sur 11.6.2 on (work's) M1, so can't upgrade to the latest OS - it would be nice (I think) to discover any issue has already been fixed there, and both QuPath and JavaCPP were fine all along.

I'll certainly let you know if I discover anything further - thanks for all your help!

**Comment by petebankhead** [comment]
I'll close this because there's now an Apple Silicon build of QuPath, other QuPath updates, JavaCPP updates, macOS updates... and I can't remember the last time I saw the problem. So let's assume it's no longer a problem at all.

Thanks!
